# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Кат1_название')),
            ],
        ),
        migrations.CreateModel(
            name='Category2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Кат2_название')),
                ('click', models.IntegerField()),
                ('cat1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi.Category1')),
            ],
        ),
        migrations.CreateModel(
            name='Category3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Кат3_название')),
                ('click', models.IntegerField()),
                ('cat1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi.Category1')),
                ('cat2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi.Category2')),
            ],
        ),
        migrations.CreateModel(
            name='IsNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isnew', models.BooleanField(default=True, verbose_name='Новое?')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.BooleanField(default=False, verbose_name='Возможность обмена')),
                ('name', models.CharField(max_length=30, verbose_name='Назв.товара')),
                ('descr', models.TextField(max_length=300, verbose_name='Детальное описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('image_main', models.ImageField(upload_to='', verbose_name='Главное изображение')),
                ('image_second', models.ImageField(upload_to='', verbose_name='Второе изображение')),
                ('image_third', models.ImageField(upload_to='', verbose_name='Третье изображение')),
                ('image_fourth', models.ImageField(upload_to='', verbose_name='Четвертое изображение')),
                ('clicks', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('reason', models.CharField(max_length=30, verbose_name='Причина продажи')),
                ('cat3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi.Category3')),
            ],
        ),
    ]
