# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category3',
            name='cat1',
        ),
    ]
